import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-franchise-development-fee-territory-reconciliation",
  "engine": "recovery",
  "title": "Franchise Development Fee & Territory Reconciliation",
  "shortTitle": "Franchise Development Fee and Territory Reconciliation",
  "tagline": "Recover franchise development fees and enforce territory and unit-opening obligations across development schedules.",
  "industry": "Franchise Revenue Assurance",
  "buyer": "Franchisors and multi-brand operators",
  "uiPort": 4734,
  "apiPort": 5734,
  "accent": "#7e22ce",
  "currency": "USD",
  "primaryOutcome": "Franchise Development Fee & Territory Reconciliation converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect development agreements, territories, unit schedules, site approvals, opening dates, initial fees, renewal fees, transfer fees, defaults, invoices, and payments in one accountable workflow. Recover franchise development fees and enforce territory and unit-opening obligations across development schedules.",
  "calculation": {
    "actualKey": "receivedAmount",
    "expectedKey": "entitledAmount",
    "actualLabel": "Received or Recognized Amount",
    "expectedLabel": "Contract or Rule-Supported Entitlement",
    "varianceLabel": "Unrecovered supported value",
    "direction": "expected-minus-actual",
    "finding": "Franchise Development Fee & Territory Reconciliation evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective agreement, eligibility rules, and accountable parties",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare the correction, recovery, or compliance package",
      "Track counterparty response, approval, cash, and preventive control closure"
    ]
  }
},[
feature("development-agreement-library","FDF01","Development agreement library","Execute development agreement library using development agreements, territories, unit schedules, site approvals, opening dates, initial fees, renewal fees, transfer fees, defaults, invoices, and payments.","Produce a governed development agreement library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Franchisee / Development Area","text","Franchisee / Development Area · Standard Case"],["caseReference","Development agreement library Reference","text","FDF01-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1758750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2128088],["domainDriver","Fee Event","select","Initial franchise",["Initial franchise","Renewal","Transfer"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Development agreement library case","Territory boundary mapping case","Franchisee entity registry case","Unit schedule tracking case","Site approval milestones case"]}),
feature("territory-boundary-mapping","FDF02","Territory boundary mapping","Execute territory boundary mapping using development agreements, territories, unit schedules, site approvals, opening dates, initial fees, renewal fees, transfer fees, defaults, invoices, and payments.","Produce a governed territory boundary mapping decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Franchisee / Development Area","text","Franchisee / Development Area · Standard Case"],["caseReference","Territory boundary mapping Reference","text","FDF02-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1758750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2128088],["domainDriver","Fee Event","select","Initial franchise",["Initial franchise","Renewal","Transfer"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Development agreement library case","Territory boundary mapping case","Franchisee entity registry case","Unit schedule tracking case","Site approval milestones case"]}),
feature("franchisee-entity-registry","FDF03","Franchisee entity registry","Execute franchisee entity registry using development agreements, territories, unit schedules, site approvals, opening dates, initial fees, renewal fees, transfer fees, defaults, invoices, and payments.","Produce a governed franchisee entity registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Franchisee / Development Area","text","Franchisee / Development Area · Standard Case"],["caseReference","Franchisee entity registry Reference","text","FDF03-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1758750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2128088],["domainDriver","Fee Event","select","Initial franchise",["Initial franchise","Renewal","Transfer"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Development agreement library case","Territory boundary mapping case","Franchisee entity registry case","Unit schedule tracking case","Site approval milestones case"]}),
feature("unit-schedule-tracking","FDF04","Unit schedule tracking","Execute unit schedule tracking using development agreements, territories, unit schedules, site approvals, opening dates, initial fees, renewal fees, transfer fees, defaults, invoices, and payments.","Produce a governed unit schedule tracking decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Franchisee / Development Area","text","Franchisee / Development Area · Standard Case"],["caseReference","Unit schedule tracking Reference","text","FDF04-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1758750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2128088],["domainDriver","Fee Event","select","Initial franchise",["Initial franchise","Renewal","Transfer"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Development agreement library case","Territory boundary mapping case","Franchisee entity registry case","Unit schedule tracking case","Site approval milestones case"]}),
feature("site-approval-milestones","FDF05","Site approval milestones","Execute site approval milestones using development agreements, territories, unit schedules, site approvals, opening dates, initial fees, renewal fees, transfer fees, defaults, invoices, and payments.","Produce a governed site approval milestones decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Franchisee / Development Area","text","Franchisee / Development Area · Standard Case"],["caseReference","Site approval milestones Reference","text","FDF05-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1758750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2128088],["domainDriver","Fee Event","select","Initial franchise",["Initial franchise","Renewal","Transfer"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Development agreement library case","Territory boundary mapping case","Franchisee entity registry case","Unit schedule tracking case","Site approval milestones case"]}),
feature("opening-deadline-control","FDF06","Opening deadline control","Execute opening deadline control using development agreements, territories, unit schedules, site approvals, opening dates, initial fees, renewal fees, transfer fees, defaults, invoices, and payments.","Produce a governed opening deadline control decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Franchisee / Development Area","text","Franchisee / Development Area · Standard Case"],["caseReference","Opening deadline control Reference","text","FDF06-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1758750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2128088],["domainDriver","Fee Event","select","Initial franchise",["Initial franchise","Renewal","Transfer"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Development agreement library case","Territory boundary mapping case","Franchisee entity registry case","Unit schedule tracking case","Site approval milestones case"]}),
feature("initial-fee-calculation","FDF07","Initial fee calculation","Execute initial fee calculation using development agreements, territories, unit schedules, site approvals, opening dates, initial fees, renewal fees, transfer fees, defaults, invoices, and payments.","Produce a governed initial fee calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Franchisee / Development Area","text","Franchisee / Development Area · Standard Case"],["caseReference","Initial fee calculation Reference","text","FDF07-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1758750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2128088],["domainDriver","Fee Event","select","Initial franchise",["Initial franchise","Renewal","Transfer"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Development agreement library case","Territory boundary mapping case","Franchisee entity registry case","Unit schedule tracking case","Site approval milestones case"]}),
feature("renewal-fee-calculation","FDF08","Renewal fee calculation","Execute renewal fee calculation using development agreements, territories, unit schedules, site approvals, opening dates, initial fees, renewal fees, transfer fees, defaults, invoices, and payments.","Produce a governed renewal fee calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Franchisee / Development Area","text","Franchisee / Development Area · Standard Case"],["caseReference","Renewal fee calculation Reference","text","FDF08-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1758750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2128088],["domainDriver","Fee Event","select","Initial franchise",["Initial franchise","Renewal","Transfer"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Development agreement library case","Territory boundary mapping case","Franchisee entity registry case","Unit schedule tracking case","Site approval milestones case"]}),
feature("transfer-fee-calculation","FDF09","Transfer fee calculation","Execute transfer fee calculation using development agreements, territories, unit schedules, site approvals, opening dates, initial fees, renewal fees, transfer fees, defaults, invoices, and payments.","Produce a governed transfer fee calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Franchisee / Development Area","text","Franchisee / Development Area · Standard Case"],["caseReference","Transfer fee calculation Reference","text","FDF09-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1758750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2128088],["domainDriver","Fee Event","select","Initial franchise",["Initial franchise","Renewal","Transfer"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Development agreement library case","Territory boundary mapping case","Franchisee entity registry case","Unit schedule tracking case","Site approval milestones case"]}),
feature("development-default-detection","FDF10","Development default detection","Execute development default detection using development agreements, territories, unit schedules, site approvals, opening dates, initial fees, renewal fees, transfer fees, defaults, invoices, and payments.","Produce a governed development default detection decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Franchisee / Development Area","text","Franchisee / Development Area · Standard Case"],["caseReference","Development default detection Reference","text","FDF10-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1758750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2128088],["domainDriver","Fee Event","select","Initial franchise",["Initial franchise","Renewal","Transfer"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Development agreement library case","Territory boundary mapping case","Franchisee entity registry case","Unit schedule tracking case","Site approval milestones case"]}),
feature("notice-cure-workflow","FDF11","Notice cure workflow","Execute notice cure workflow using development agreements, territories, unit schedules, site approvals, opening dates, initial fees, renewal fees, transfer fees, defaults, invoices, and payments.","Produce a governed notice cure workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Franchisee / Development Area","text","Franchisee / Development Area · Standard Case"],["caseReference","Notice cure workflow Reference","text","FDF11-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1758750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2128088],["domainDriver","Fee Event","select","Initial franchise",["Initial franchise","Renewal","Transfer"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Development agreement library case","Territory boundary mapping case","Franchisee entity registry case","Unit schedule tracking case","Site approval milestones case"]}),
feature("invoice-generation","FDF12","Invoice generation","Execute invoice generation using development agreements, territories, unit schedules, site approvals, opening dates, initial fees, renewal fees, transfer fees, defaults, invoices, and payments.","Produce a governed invoice generation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Franchisee / Development Area","text","Franchisee / Development Area · Standard Case"],["caseReference","Invoice generation Reference","text","FDF12-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1758750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2128088],["domainDriver","Fee Event","select","Initial franchise",["Initial franchise","Renewal","Transfer"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Development agreement library case","Territory boundary mapping case","Franchisee entity registry case","Unit schedule tracking case","Site approval milestones case"]}),
feature("franchisee-dispute-workflow","FDF13","Franchisee dispute workflow","Execute franchisee dispute workflow using development agreements, territories, unit schedules, site approvals, opening dates, initial fees, renewal fees, transfer fees, defaults, invoices, and payments.","Produce a governed franchisee dispute workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Franchisee / Development Area","text","Franchisee / Development Area · Standard Case"],["caseReference","Franchisee dispute workflow Reference","text","FDF13-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1758750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2128088],["domainDriver","Fee Event","select","Initial franchise",["Initial franchise","Renewal","Transfer"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Development agreement library case","Territory boundary mapping case","Franchisee entity registry case","Unit schedule tracking case","Site approval milestones case"]}),
feature("cash-reconciliation","FDF14","Cash reconciliation","Execute cash reconciliation using development agreements, territories, unit schedules, site approvals, opening dates, initial fees, renewal fees, transfer fees, defaults, invoices, and payments.","Produce a governed cash reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Franchisee / Development Area","text","Franchisee / Development Area · Standard Case"],["caseReference","Cash reconciliation Reference","text","FDF14-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1758750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2128088],["domainDriver","Fee Event","select","Initial franchise",["Initial franchise","Renewal","Transfer"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Development agreement library case","Territory boundary mapping case","Franchisee entity registry case","Unit schedule tracking case","Site approval milestones case"]}),
feature("territory-unit-analytics","FDF15","Territory unit analytics","Execute territory unit analytics using development agreements, territories, unit schedules, site approvals, opening dates, initial fees, renewal fees, transfer fees, defaults, invoices, and payments.","Produce a governed territory unit analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Franchisee / Development Area","text","Franchisee / Development Area · Standard Case"],["caseReference","Territory unit analytics Reference","text","FDF15-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1758750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2128088],["domainDriver","Fee Event","select","Initial franchise",["Initial franchise","Renewal","Transfer"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Development agreement library case","Territory boundary mapping case","Franchisee entity registry case","Unit schedule tracking case","Site approval milestones case"]})
]);
